import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        {type: 'autogenerated', dirName: 'getting-started'},
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        {type: 'autogenerated', dirName: 'core-concepts'},
      ],
    },
    {
      type: 'category',
      label: 'Guides',
      items: [
        {type: 'autogenerated', dirName: 'guides'},
      ],
    },
    {
      type: 'category',
      label: 'Advanced Topics',
      items: [
        {type: 'autogenerated', dirName: 'advanced-topics'},
      ],
    },
  ],
};

export default sidebars;
