name: Allow target branch
on:
  pull_request:
    branches:
      - main
    types:
      - synchronize
      - opened
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check if PR can push to base branch
        run: |
          echo "Checking if PR can push to base branch"
          echo "Base branch: ${{ github.base_ref }}"
          echo "Head branch: ${{ github.head_ref }}"
          if [ ${{ github.head_ref }} != "development" ] && [ ${{ github.base_ref }} == "main" ]; then
            echo "Merge requests to main branch are only allowed from development branch."
            exit 1
          fi

      - name: Get current version
        id: current_version
        uses: ./.github/actions/composer-package-version
        if: ${{ github.base_ref }} == 'main'
        with:
          working-directory: .

      - name: Get Latest Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: Luc-cpl
          repo: orkestra

      - name: "Read Semver Info"
        id: "semver_info"
        uses: YunaBraska/semver-info-action@main
        if: ${{ github.base_ref }} == 'main'
        with:
          semver-a: ${{ steps.current_version.outputs.version }}
          semver-b: ${{ steps.latest_release.outputs.release }}

      - name: "Check Semver"
        if: ${{ github.base_ref }} == 'main'
        run: |
          echo "Checking Semver"
          echo "Semver A: ${{ steps.current_version.outputs.version }}"
          echo "Semver B: ${{ steps.latest_release.outputs.release }}"
          is_greater_a=${{ steps.semver_info.outputs.is_greater_a }}
          is_stable_a=${{ steps.semver_info.outputs.is_stable_a }}
          if [ $is_greater_a == "true" ] && [ $is_stable_a == "true" ]; then
            echo "New version is greater than main branch version"
          else
            echo "New version is not greater than main branch or is not a stable version."
            exit 1
          fi