name: Tag version

on:
  push:
    branches:
      - main

jobs:
  coverage_badge:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: Install Dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true' # Skip if cache hit
        run: composer install -q --no-interaction --no-scripts

      - name: Generate coverage results
        run: |
          composer install
          XDEBUG_MODE=coverage vendor/bin/pest --coverage-clover clover.xml

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          file: clover.xml

  tag_version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4

      - name: Get current version
        id: current_version
        uses: ./.github/actions/composer-package-version
        with:
          working-directory: .

      - name: Get Latest Release
        id: latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0
        with:
          owner: Luc-cpl
          repo: orkestra

      - name: Read Semver Info
        id: semver_info
        uses: YunaBraska/semver-info-action@main
        if: ${{ github.base_ref }} == 'main'
        with:
          semver-a: ${{ steps.current_version.outputs.version }}
          semver-b: ${{ steps.latest_release.outputs.release }}

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        if: ${{ steps.semver_info.outputs.is_greater_a == 'true' }}
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          version: ${{ steps.current_version.outputs.version }}
          release: ${{ steps.semver_info.outputs.is_stable_a }}
