name: Tag version

on:
  push:
    branches:
      - main

jobs:
  coverage_badge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Generate coverage results
        run: |
          composer install
          XDEBUG_MODE=coverage vendor/bin/pest --coverage-clover clover.xml

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          mkdir -p coveralls && cd coveralls
          composer init --no-interaction --name=local/coveralls
          composer require php-coveralls/php-coveralls --no-suggest --no-progress
          vendor/bin/php-coveralls --coverage_clover=../clover.xml -v

  tag_version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - uses: actions/checkout@v4

      - name: Get current version
        id: version
        uses: ./.github/actions/composer-package-version
        with:
          working-directory: .

      - name: Push tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN }}"
          WITH_V: "${{ steps.version.outputs.version }}"